apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default  # 실제 네임스페이스에 맞게 수정
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: flask
